INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.enquete_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	false,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.enquete_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	false,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.enquete_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	true,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.enquete_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	true,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.enquete_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	false,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.opcao_id_seq,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.enquete_id_seq'));