INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.ENQUETE_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	false,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.ENQUETE_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	false,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.ENQUETE_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	true,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.ENQUETE_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	true,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));

INSERT INTO ENQUETE VALUES(	NEXT VALUE FOR PUBLIC.ENQUETE_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	false,	false,	'Qual a sua cor preferida?',	'ABC123ABC123ABC123ABC123ABC123'); 
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Azul',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));
INSERT INTO OPCAO VALUES ( NEXT VALUE FOR PUBLIC.OPCAO_SEQ,	CURRENT_TIMESTAMP,	CURRENT_TIMESTAMP,	'Vermelho',	0,	SELECT CURRVAL('PUBLIC.ENQUETE_SEQ'));